apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: civdle-ingress
  namespace: civdle
  labels:
    app: civdle
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - civdle.bevsoft.com
      secretName: civdle-tls
  rules:
    - host: civdle.bevsoft.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: civdle
                port:
                  number: 80
